In [141]:
import numpy as np

In [142]:
my_list = [1,2,3,4,5]
my_array = np.array(my_list)

In [143]:
print("Numpy Array: ", my_array)
print("Type: ", type(my_array))

Numpy Array:  [1 2 3 4 5]
Type:  <class 'numpy.ndarray'>


In [144]:
#shape 
print(my_array.shape)
#datatype
print(my_array.dtype)

(5,)
int64


In [145]:
py_list = [1,2,3,4,5]

np_array = np.array([1,2,3,4,5])


In [146]:
print("List addition: ", [x + 1 for x in py_list])
print("Array addition: ", [np_array + 1])


List addition:  [2, 3, 4, 5, 6]
Array addition:  [array([2, 3, 4, 5, 6])]


In [147]:
numbers = np.arange(11)
doubled = numbers * 2
total = np.sum(numbers)

print("Original Array: ", numbers)
print("Doubled Array: ", doubled)
print("Sum of Elements: ", total)

Original Array:  [ 0  1  2  3  4  5  6  7  8  9 10]
Doubled Array:  [ 0  2  4  6  8 10 12 14 16 18 20]
Sum of Elements:  55


In [148]:
# basic functions to master...
#np.zeros() , creates an array filled with zeros
#np.ones(), creates an array filled with ones
#np. arange(), generates a range of numbers
#np.linspace(), generates numbers evenly spaced beween a start and stop value,

print("Array of zeros", np.zeros(5))
print("Array of ones", np.ones(5))
print("Array of numbers from 0, 6", np.arange(0, 7, 1))
print("Linearly spaced numbers", np.linspace(0, 1, 5))

Array of zeros [0. 0. 0. 0. 0.]
Array of ones [1. 1. 1. 1. 1.]
Array of numbers from 0, 6 [0 1 2 3 4 5 6]
Linearly spaced numbers [0.   0.25 0.5  0.75 1.  ]


In [149]:
# advancedarray init

#random array
random_array = np.random.random(6)
print(random_array)
random_integers = np.random.randint(69, 96, size=5)
print(random_integers)

#identity matrix 
identity_matrix = np.eye(3)
print(identity_matrix)




[0.86922488 0.55717032 0.9620233  0.30872798 0.26640398 0.1663303 ]
[84 86 70 71 85]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [150]:
#diag_Matrix 
diag_matrix = np.diag([1,2,3])
print(diag_matrix)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [151]:
custom_dtype_array = np.array([1,2,3], dtype=np.int64)
print(custom_dtype_array)
print(type(custom_dtype_array[0]))

[1 2 3]
<class 'numpy.int64'>


In [152]:
# Create a sample array
arr = np.array([10, 20, 30, 40, 50])

# Basic Properties
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data Type:", arr.dtype)
print("Dimension:", arr.ndim)

# Indexing and Slicing
print("First Element:", arr[0])       # Indexing
print("Last Element:", arr[-1])      # Negative Indexing
print("Sub-array:", arr[2:4])        # Slicing

# Reverse an Array
print("Reversed Array:", arr[::-1])

# Boolean Indexing
print("Elements > 20:", arr[arr > 20])

# Fancy Indexing
print("Select Specific Indices [0, 2, 4]:", arr[[0, 2, 4]])


Shape: (5,)
Size: 5
Data Type: int64
Dimension: 1
First Element: 10
Last Element: 50
Sub-array: [30 40]
Reversed Array: [50 40 30 20 10]
Elements > 20: [30 40 50]
Select Specific Indices [0, 2, 4]: [10 30 50]


In [153]:
# practice task
random_array = np.random.randint(0, 100, size=10)
print(random_array)

reversed_random_array = random_array[::-1]
print(reversed_random_array)

even_numbers = random_array[random_array % 2 == 0]
print(even_numbers)

[77  3 41  6 49  0 93 63 56 29]
[29 56 63 93  0 49  6 41  3 77]
[ 6  0 56]


In [154]:
arr = np.array([1,2,3,4,5])
print("original array: ", arr)

result = arr + 10
print(result)

original array:  [1 2 3 4 5]
[11 12 13 14 15]


In [155]:
a = np.array([1,2,3])
b = np.array([[10], [20], [30]])
print(a.shape)
print(b.shape)

broadcast_result = a + b
print(broadcast_result)
print(broadcast_result.shape)



(3,)
(3, 1)
[[11 12 13]
 [21 22 23]
 [31 32 33]]
(3, 3)


In [156]:
# views vs copies
original = np.array([1,2,3,4])

view = original[1:3]
print("View before modification: ", view)

view[0] = 99
print("View after modification:", view)

print("Original", original)

copy = original[1:3].copy()
print("Copy before modification: ", copy)

copy[0] = 43
print("Copy after modification: ", copy)

print("original: ", original)


View before modification:  [2 3]
View after modification: [99  3]
Original [ 1 99  3  4]
Copy before modification:  [99  3]
Copy after modification:  [43  3]
original:  [ 1 99  3  4]


In [157]:
# advanced indexing
matrix = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

# Access element at row 1, column 2
print("Element [0, 1]:", matrix[0, 1])

# Extract a speicif row
print("First row: ", matrix[0, :])

# Extract a specific column
print("Second column: ", matrix[:, 1])

# Extract a sub matrix 
print("Sub matrix: ", matrix[1:3, 1:])


Element [0, 1]: 20
First row:  [10 20 30]
Second column:  [20 50 80]
Sub matrix:  [[50 60]
 [80 90]]


In [158]:
# boolean masking

mask = matrix > 50
print("Boolean mask:\n", mask)

filtered = matrix[mask]
print("Filtered elems: ", filtered)


Boolean mask:
 [[False False False]
 [False False  True]
 [ True  True  True]]
Filtered elems:  [60 70 80 90]


In [159]:
# linear alg ops

A = np.array([
  [1,2], 
  [3,4]
])

B = np.array([
  [5,6],
  [7,8]
])

C = np.dot(A, B)
print("Matrix Multiplication:\n", C)

print("Transpose", A.T)

Matrix Multiplication:
 [[19 22]
 [43 50]]
Transpose [[1 3]
 [2 4]]


In [160]:
# Data type manipulation
arr = np.array([1,2,3])

float_arr = arr.astype(float)
print("float arr: ", type(float_arr[0]))
str_arr = arr.astype(str)
print("String_arry", type(str_arr[0]))

float arr:  <class 'numpy.float64'>
String_arry <class 'numpy.str_'>


In [161]:
# you can control how arrays are stored in memory, there are tow ways, c order row major and f order which i s column major

# Create an array with C-order (row-major)
c_order = np.array([[1, 2], [3, 4]], order='C')
print("C-Order Array:\n", c_order)

# Create an array with F-order (column-major)
f_order = np.array([[1, 2], [3, 4]], order='F')
print("F-Order Array:\n", f_order)

C-Order Array:
 [[1 2]
 [3 4]]
F-Order Array:
 [[1 2]
 [3 4]]


In [162]:
# reshaping and flattening

arr = np.arange(12)

#reshape into 3*4
reshaped = arr.reshape(3, 4)
print(reshaped)


#flatten back into 1D
flattened = reshaped.flatten()
print(flattened)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [163]:
arr = np.array([10,20,30,40,50])

print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

150
30.0
30.0
14.142135623730951


In [164]:
# practice tasks
arr = np.random.randint(0, 100, size=(4,4))
print("original_arr", arr)


original_arr [[21 34 61 72]
 [11 65  8 84]
 [12 24  0 49]
 [72 53 24 93]]


In [165]:
last_column = arr[: , 3]
print("Last column", last_column)

Last column [72 84 49 93]


In [166]:
print("mean of the entire array: ", np.mean(arr))


mean of the entire array:  42.6875


In [168]:
row_reversed_array = arr[::-1, :]
print(row_reversed_array)

[[72 53 24 93]
 [12 24  0 49]
 [11 65  8 84]
 [21 34 61 72]]


In [170]:
y = np.random.randint(0, 100, size=(3,3,3))
y


array([[[40, 23, 44],
        [ 4, 21, 82],
        [25, 19, 87]],

       [[23, 53, 62],
        [47, 49, 32],
        [47, 36, 33]],

       [[94, 31,  1],
        [82, 29, 50],
        [20, 27, 83]]], dtype=int32)

In [175]:
sum0 = np.sum(y, axis=0)
print(sum0)
sum1 = np.sum(y, axis=1)
print(sum0)
sum2 = np.sum(y, axis=2)
print(sum0)


flattened = y.flatten()
print(flattened)

[[157 107 107]
 [133  99 164]
 [ 92  82 203]]
[[157 107 107]
 [133  99 164]
 [ 92  82 203]]
[[157 107 107]
 [133  99 164]
 [ 92  82 203]]
[40 23 44  4 21 82 25 19 87 23 53 62 47 49 32 47 36 33 94 31  1 82 29 50
 20 27 83]
